### ISSUE TITLE
Moving around some docs for an easier integration

### ISSUE THREAD

**Issue by BDonnot** [jhmenke/grid2op_pp_baseline#1]
Hello Jan Hendrick,

Would it be possible for you to have all your baseline code in the github repostiory.
This would look like:
```
.gitignore
LICENSE
Readme.md
info.md
__init__.py
evaluate.py
pandapowerOPFAgent.py
pp_functions.py
```

So that we can directly add a directory "pandapowerOPF" into l2rpn-baselines that would be a "symbolic link" (ie a submodule) containing your code, the license and all ?

Thanks a lot :-)

Benjamin

**Comment by BDonnot** [comment]
I made the PR #2 as an example :-)

**Comment by jhmenke** [comment]
Thanks! You were faster than me. I also merged Info.md into the README.md

**Comment by BDonnot** [comment]
No problem :-)
I'll try to integrate it into the baseline today !

Have a great day

Benjamin
